18:15: fractrig $ python3 manage.py shell
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import os
>>> image_list = list(os.walk('./static/images/zarg438/'))[0][2]
>>> len(image_list)
348
>>> im = image_list[0]
>>> im
'xtsM2f353C451-438x310x0.0y0.0_65185.png'
>>> from fract.models import Image
>>> for name in image_list:
...     img = Image(name=name, size='438x310')
...     img.save()
... 
>>> 

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

To push the content to the remote database I tried 
`heroku pg:push db.sqlite3 postgresql-crystalline-18465 -a ztrif`
unsuccessfully.   Needed
`sudo apt install postgresql`
Reset database and tried again, unsuccessfully.
Still failed with "role 'john' does not exist".

So, now tried by running the code on the server, with list generated locally.
Seems to have screwed up the database, so i will try to redo migrations locally then push to Heroku.

find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
find . -path "*/migrations/*.pyc"  -delete
rm -r db.sqlite3

python3 manage.py
####### failed with `ModuleNotFoundError: No module named 'django.db.migrations.migration'`
So tried upgrading Django...

pip install --upgrade django==2.2


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Later...

Adding image data to the database:

02:25: fractrig $ python3 manage.py shell
In DEVELOPMENT context
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from fract import add_images
Enter directory string: fract/test
Directory: fract/test.   Continue? y/ny
xtsJ1f353C401-pre60-sri-438x310x-3.036256350301346y-1.4303025782411303_5841.png saved.
Done.   1 image names saved in the database.





